"""add unique constraint to event seats

Revision ID: b2932c958541
Revises: ac5337d13c6c
Create Date: 2026-06-30 20:49:19.021079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2932c958541'
down_revision: Union[str, Sequence[str], None] = 'ac5337d13c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_seat_event_row_number', 'seats', ['event_id', 'row', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_seat_event_row_number', 'seats', type_='unique')
    # ### end Alembic commands ###
