"""add payment attempts

Revision ID: da75b44797a0
Revises: af3b89641dbe
Create Date: 2026-07-18 17:24:43.378766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da75b44797a0"
down_revision: Union[str, Sequence[str], None] = "af3b89641dbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hold_id", sa.Integer(), nullable=True),
        sa.Column("booking_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("seat_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "creating",
                "pending",
                "succeeded",
                "failed",
                "expired",
                "requires_refund",
                name="payment_attempt_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="creating",
            nullable=False,
        ),
        sa.Column("stripe_checkout_session_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("checkout_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount >= 0", name="ck_payment_attempts_amount_non_negative"
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3", name="ck_payment_attempts_currency_length"
        ),
        sa.CheckConstraint(
            "currency = lower(currency)", name="ck_payment_attempts_currency_lowercase"
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hold_id"], ["holds.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["seat_id"],
            ["seats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id", name="uq_payment_attempts_booking_id"),
        sa.UniqueConstraint(
            "stripe_checkout_session_id", name="uq_payment_attempts_checkout_session_id"
        ),
        sa.UniqueConstraint(
            "stripe_payment_intent_id", name="uq_payment_attempts_payment_intent_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_attempts")
    # ### end Alembic commands ###
